#!/usr/bin/env 
# -*- coding: utf-8 -*-

dogs = {
1: {'breed_id':1, 'breed_name': u"Австралийская короткохвостая пастушья"},
2: {'breed_id':2, 'breed_name': u"Австралийская овчарка"},
3: {'breed_id':3, 'breed_name': u"Австралийский шелковистый терьер"},
4: {'breed_id':4, 'breed_name': u"Акита ину"},
5: {'breed_id':5, 'breed_name': u"Аляскинский маламут"},
6: {'breed_id':6, 'breed_name': u"Американская акита"},
7: {'breed_id':7, 'breed_name': u"Американский бульдог"},
8: {'breed_id':8, 'breed_name': u"Американский кокер спаниель"},
9: {'breed_id':9, 'breed_name': u"Американский питбультерьер"},
10: {'breed_id':10, 'breed_name': u"Американский стаффордширский терьер"},
11: {'breed_id':11, 'breed_name': u"Американский той фокстерьер"},
12: {'breed_id':12, 'breed_name': u"Английский бульдог"},
13: {'breed_id':13, 'breed_name': u"Английский кокер спаниель"},
14: {'breed_id':14, 'breed_name': u"Английский мастиф"},
15: {'breed_id':15, 'breed_name': u"Английский пойнтер"},
16: {'breed_id':16, 'breed_name': u"Английский сеттер"},
17: {'breed_id':17, 'breed_name': u"Аргентинский дог"},
18: {'breed_id':18, 'breed_name': u"Афганская борзая"},
19: {'breed_id':19, 'breed_name': u"Аффенпинчер"},
20: {'breed_id':20, 'breed_name': u"Басенджи"},
21: {'breed_id':21, 'breed_name': u"Бассет хаунд"},
22: {'breed_id':22, 'breed_name': u"Бедлингтон терьер"},
23: {'breed_id':23, 'breed_name': u"Белая швейцарская овчарка"},
24: {'breed_id':24, 'breed_name': u"Бельгийская овчарка малинуа"},
25: {'breed_id':25, 'breed_name': u"Бельгийский гриффон"},
26: {'breed_id':26, 'breed_name': u"Бернский зенненхунд"},
27: {'breed_id':27, 'breed_name': u"Бивер йорк"},
28: {'breed_id':28, 'breed_name': u"Бигль"},
29: {'breed_id':29, 'breed_name': u"Бишон фризе"},
30: {'breed_id':30, 'breed_name': u"Бобтейл (староанглийская овчарка)"},
31: {'breed_id':31, 'breed_name': u"Боксер (немецкий)"},
32: {'breed_id':32, 'breed_name': u"Болонез (болонский бишон)"},
33: {'breed_id':33, 'breed_name': u"Большая пиренейская"},
34: {'breed_id':34, 'breed_name': u"Бордер колли"},
35: {'breed_id':35, 'breed_name': u"Бордер терьер"},
36: {'breed_id':36, 'breed_name': u"Бордоский дог"},
37: {'breed_id':37, 'breed_name': u"Бородатая колли"},
38: {'breed_id':38, 'breed_name': u"Босерон"},
39: {'breed_id':39, 'breed_name': u"Бостон терьер"},
40: {'breed_id':40, 'breed_name': u"Бриар (французская овчарка)"},
41: {'breed_id':41, 'breed_name': u"Брюссельский гриффон"},
42: {'breed_id':42, 'breed_name': u"Бульмастиф"},
43: {'breed_id':43, 'breed_name': u"Бультерьер"},
44: {'breed_id':44, 'breed_name': u"Веймаранер (веймарская легавая)"},
45: {'breed_id':45, 'breed_name': u"Вельш корги кардиган"},
46: {'breed_id':46, 'breed_name': u"Вельш корги пемброк"},
47: {'breed_id':47, 'breed_name': u"Вельш терьер"},
48: {'breed_id':48, 'breed_name': u"Венгерская короткошерстная легавая (выжла)"},
49: {'breed_id':49, 'breed_name': u"Вест хайленд уайт терьер"},
50: {'breed_id':50, 'breed_name': u"Восточно-европейская овчарка"},
51: {'breed_id':51, 'breed_name': u"Восточносибирская лайка"},
52: {'breed_id':52, 'breed_name': u"Гладкошёрстный фокстерьер"},
53: {'breed_id':53, 'breed_name': u"Грейхаунд"},
54: {'breed_id':54, 'breed_name': u"Гриффон кортальса"},
55: {'breed_id':55, 'breed_name': u"Далматин"},
56: {'breed_id':56, 'breed_name': u"Денди динмонт терьер"},
57: {'breed_id':57, 'breed_name': u"Джек рассел терьер"},
58: {'breed_id':58, 'breed_name': u"Доберман"},
59: {'breed_id':59, 'breed_name': u"Дратхаар"},
60: {'breed_id':60, 'breed_name': u"Западносибирская лайка"},
61: {'breed_id':61, 'breed_name': u"Золотистый (голден) ретривер"},
62: {'breed_id':62, 'breed_name': u"Ирландский волкодав"},
63: {'breed_id':63, 'breed_name': u"Ирландский мягкошерстный пшеничный терьер"},
64: {'breed_id':64, 'breed_name': u"Ирландский сеттер"},
65: {'breed_id':65, 'breed_name': u"Ирландский терьер"},
66: {'breed_id':66, 'breed_name': u"Испанский мастиф"},
67: {'breed_id':67, 'breed_name': u"Итальянский бракк"},
68: {'breed_id':68, 'breed_name': u"Йоркширский терьер"},
69: {'breed_id':69, 'breed_name': u"Кавалер кинг чарльз спаниель"},
70: {'breed_id':70, 'breed_name': u"Кавказская овчарка"},
71: {'breed_id':71, 'breed_name': u"Ка Де Бо"},
72: {'breed_id':72, 'breed_name': u"Канарская"},
73: {'breed_id':73, 'breed_name': u"Итальянский кане корсо"},
74: {'breed_id':74, 'breed_name': u"Карело-финская лайка"},
75: {'breed_id':75, 'breed_name': u"Карликовый пинчер (цвергпинчер)"},
76: {'breed_id':76, 'breed_name': u"Немецкий шпиц (Кеесхонд)"},
77: {'breed_id':77, 'breed_name': u"Керн терьер"},
78: {'breed_id':78, 'breed_name': u"Керри блю терьер"},
79: {'breed_id':79, 'breed_name': u"Китайская хохлатая собака"},
80: {'breed_id':80, 'breed_name': u"Кламбер спаниель"},
81: {'breed_id':81, 'breed_name': u"Колли длинношерстная (шотландская овчарка)"},
82: {'breed_id':82, 'breed_name': u"Комондор"},
83: {'breed_id':83, 'breed_name': u"Лабрадор ретривер"},
84: {'breed_id':84, 'breed_name': u"Левретка (итальянский грейхаунд)"},
85: {'breed_id':85, 'breed_name': u"Леонбергер"},
86: {'breed_id':86, 'breed_name': u"Лхаский апсо"},
87: {'breed_id':87, 'breed_name': u"Мальтезе (мальтийская болонка)"},
88: {'breed_id':88, 'breed_name': u"Мареммо-абруцкая овчарка"},
89: {'breed_id':89, 'breed_name': u"Мексиканская голая собака"},
90: {'breed_id':90, 'breed_name': u"Метис"},
91: {'breed_id':91, 'breed_name': u"Миниатюрный бультерьер"},
92: {'breed_id':92, 'breed_name': u"Миттельшнауцер"},
93: {'breed_id':93, 'breed_name': u"Мопс"},
94: {'breed_id':94, 'breed_name': u"Московская сторожевая"},
95: {'breed_id':95, 'breed_name': u"Неаполитанский мастиф"},
96: {'breed_id':96, 'breed_name': u"Немецкая овчарка длинношерстная"},
97: {'breed_id':97, 'breed_name': u"Немецкая овчарка"},
98: {'breed_id':98, 'breed_name': u"Немецкий дог"},
99: {'breed_id':99, 'breed_name': u"Немецкий курцхаар"},
100: {'breed_id':100, 'breed_name': u"Немецкий шпиц (Малый)"},
101: {'breed_id':101, 'breed_name': u"Немецкий шпиц (Средний)"},
102: {'breed_id':102, 'breed_name': u"Немецкий ягдтерьер"},
103: {'breed_id':103, 'breed_name': u"Норвич терьер"},
104: {'breed_id':104, 'breed_name': u"Ньюфаундленд"},
105: {'breed_id':105, 'breed_name': u"Континентальный спаниель (папийон, фален)"},
106: {'breed_id':106, 'breed_name': u"Парсон рассел терьер"},
107: {'breed_id':107, 'breed_name': u"Пекинес"},
108: {'breed_id':108, 'breed_name': u"Перуанская голая собака"},
109: {'breed_id':109, 'breed_name': u"Петербургская орхидея"},
110: {'breed_id':110, 'breed_name': u"Пинчер немецкий"},
111: {'breed_id':111, 'breed_name': u"Пиренейская овчарка длинношерстная"},
112: {'breed_id':112, 'breed_name': u"Польская подгалянская овчарка"},
113: {'breed_id':113, 'breed_name': u"Немецкий шпиц (Померанский)"},
114: {'breed_id':114, 'breed_name': u"Пражский крысарик"},
115: {'breed_id':115, 'breed_name': u"Прямошерстный ретривер"},
116: {'breed_id':116, 'breed_name': u"Пти брабансон"},
117: {'breed_id':117, 'breed_name': u"Пудель большой (стандартный королевский пудель)"},
118: {'breed_id':118, 'breed_name': u"Пудель карликовый (миниатюрный)"},
119: {'breed_id':119, 'breed_name': u"Пудель малый"},
120: {'breed_id':120, 'breed_name': u"Пудель той"},
121: {'breed_id':121, 'breed_name': u"Ризеншнауцер"},
122: {'breed_id':122, 'breed_name': u"Родезийский риджбек"},
123: {'breed_id':123, 'breed_name': u"Ротвейлер"},
124: {'breed_id':124, 'breed_name': u"Русская гончая"},
125: {'breed_id':125, 'breed_name': u"Русская пегая гончая"},
126: {'breed_id':126, 'breed_name': u"Русская псовая борзая"},
127: {'breed_id':127, 'breed_name': u"Русская цветная болонка"},
128: {'breed_id':128, 'breed_name': u"Русский охотничий спаниель"},
129: {'breed_id':129, 'breed_name': u"Русский той терьер"},
130: {'breed_id':130, 'breed_name': u"Русско-европейская лайка"},
131: {'breed_id':131, 'breed_name': u"Салюки (арабская борзая)"},
132: {'breed_id':132, 'breed_name': u"Самоед (самоедская собака)"},
133: {'breed_id':133, 'breed_name': u"Сенбернар"},
134: {'breed_id':134, 'breed_name': u"Сеттер гордон (шотландский)"},
135: {'breed_id':135, 'breed_name': u"Сиба-ину"},
136: {'breed_id':136, 'breed_name': u"Сибирская ездовая собака"},
137: {'breed_id':137, 'breed_name': u"Силихем терьер"},
138: {'breed_id':138, 'breed_name': u"Скай терьер"},
139: {'breed_id':139, 'breed_name': u"Скотч терьер"},
140: {'breed_id':140, 'breed_name': u"Словацкий чувач"},
141: {'breed_id':141, 'breed_name': u"Английский спрингер спаниель"},
142: {'breed_id':142, 'breed_name': u"Среднеазиатская овчарка (алабай)"},
143: {'breed_id':143, 'breed_name': u"Стаффордширский бультерьер"},
144: {'breed_id':144, 'breed_name': u"Тайский риджбек"},
145: {'breed_id':145, 'breed_name': u"Такса гладкошерстная"},
146: {'breed_id':146, 'breed_name': u"Такса жесткошерстная"},
147: {'breed_id':147, 'breed_name': u"Такса карликовая"},
148: {'breed_id':148, 'breed_name': u"Такса кроличья"},
149: {'breed_id':149, 'breed_name': u"Такса стандартная"},
150: {'breed_id':150, 'breed_name': u"Тибетский мастиф"},
151: {'breed_id':151, 'breed_name': u"Тибетский спаниель"},
152: {'breed_id':152, 'breed_name': u"Тибетский терьер"},
153: {'breed_id':153, 'breed_name': u"Английский той терьер"},
154: {'breed_id':154, 'breed_name': u"Тувинская овчарка"},
155: {'breed_id':155, 'breed_name': u"Уиппет"},
156: {'breed_id':156, 'breed_name': u"Фараонова собака"},
157: {'breed_id':157, 'breed_name': u"Финская гончая"},
158: {'breed_id':158, 'breed_name': u"Фландрский бувье"},
159: {'breed_id':159, 'breed_name': u"Фокстерьер гладкошерстный"},
160: {'breed_id':160, 'breed_name': u"Фокстерьер жесткошерстный"},
161: {'breed_id':161, 'breed_name': u"Французский бульдог"},
162: {'breed_id':162, 'breed_name': u"Хаски (сибирский)"},
163: {'breed_id':163, 'breed_name': u"Ховаварт"},
164: {'breed_id':164, 'breed_name': u"Хортая борзая"},
165: {'breed_id':165, 'breed_name': u"Цвергшнауцер"},
166: {'breed_id':166, 'breed_name': u"Чау-чау"},
167: {'breed_id':167, 'breed_name': u"Русский черный терьер"},
168: {'breed_id':168, 'breed_name': u"Чехословацкая волчья собака"},
169: {'breed_id':169, 'breed_name': u"Чихуахуа"},
170: {'breed_id':170, 'breed_name': u"Шарпей"},
171: {'breed_id':171, 'breed_name': u"Шелти"},
172: {'breed_id':172, 'breed_name': u"Ши тцу"},
174: {'breed_id':174, 'breed_name': u"Шипперке"},
175: {'breed_id':175, 'breed_name': u"Энтлебухер зенненхунд"},
176: {'breed_id':176, 'breed_name': u"Эрдельтерьер"},
177: {'breed_id':177, 'breed_name': u"Эстонская гончая"},
178: {'breed_id':178, 'breed_name': u"Южноафриканский бурбуль"},
179: {'breed_id':179, 'breed_name': u"Южнорусская овчарка"},
180: {'breed_id':180, 'breed_name': u"Ягдтерьер"},
181: {'breed_id':181, 'breed_name': u"Японский хин"},
182: {'breed_id':182, 'breed_name': u"Японский шпиц"},
183: {'breed_id':183, 'breed_name': u"Русская салонная собака (русалка)"},
184: {'breed_id':184, 'breed_name': u"Норфолк терьер"},
185: {'breed_id':185, 'breed_name': u"Немецкий шпиц (Большой)"},
}
