#!/usr/bin/python
# -*- coding: utf-8 -*-


regions = {
-25 : { "region_id" : -25, "region_name" : u"Ульяновская область", "region_name_i" : u"Ульяновская область", "region_name_r" : u"Ульяновской области", "region_name_d" : u"Ульяновской области", "region_name_v" : u"Ульяновскую область", "region_name_t" : u"Ульяновской областью", "region_name_p" : u"Ульяновской области"},
-99 : { "region_id" : -99, "region_name" : u"Усть-Ордынский Бурятский авт. окр.", "region_name_i" : u"Усть-Ордынский Бурятский авт. окр.", "region_name_r" : u"Усть-Ордынский Бурятский авт. окр.", "region_name_d" : u"Усть-Ордынский Бурятский авт. окр.", "region_name_v" : u"Усть-Ордынский Бурятский авт. окр.", "region_name_t" : u"Усть-Ордынский Бурятский авт. окр.", "region_name_p" : u"Усть-Ордынском Бурятском авт. окр."},
-23 : { "region_id" : -23, "region_name" : u"Томская область", "region_name_i" : u"Томская область", "region_name_r" : u"Томской области", "region_name_d" : u"Томской области", "region_name_v" : u"Томскую область", "region_name_t" : u"Томской областью", "region_name_p" : u"Томской области"},
-1 : { "region_id" : -1, "region_name" : u"Московская область", "region_name_i" : u"Московская область", "region_name_r" : u"Московской области", "region_name_d" : u"Московской области", "region_name_v" : u"Московскую область", "region_name_t" : u"Московской областью", "region_name_p" : u"Московской области"},
-92 : { "region_id" : -92, "region_name" : u"Чукотский авт. окр.", "region_name_i" : u"Чукотский авт. окр.", "region_name_r" : u"Чукотский авт. окр.", "region_name_d" : u"Чукотский авт. окр.", "region_name_v" : u"Чукотский авт. окр.", "region_name_t" : u"Чукотский авт. окр.", "region_name_p" : u"Чукотском авт. окр."},
-90 : { "region_id" : -90, "region_name" : u"Коми-Пермяцкий авт. окр.", "region_name_i" : u"Коми-Пермяцкий авт. окр.", "region_name_r" : u"Коми-Пермяцкий авт. окр.", "region_name_d" : u"Коми-Пермяцкий авт. окр.", "region_name_v" : u"Коми-Пермяцкий авт. окр.", "region_name_t" : u"Коми-Пермяцкий авт. окр.", "region_name_p" : u"Коми-Пермяцком авт. окр."},
-89 : { "region_id" : -89, "region_name" : u"Еврейская авт. область", "region_name_i" : u"Еврейская авт. область", "region_name_r" : u"Еврейская авт. область", "region_name_d" : u"Еврейская авт. область", "region_name_v" : u"Еврейская авт. область", "region_name_t" : u"Еврейская авт. область", "region_name_p" : u"Еврейской авт. область"},
-88 : { "region_id" : -88, "region_name" : u"Ярославская область", "region_name_i" : u"Ярославская область", "region_name_r" : u"Ярославской области", "region_name_d" : u"Ярославской области", "region_name_v" : u"Ярославскую область", "region_name_t" : u"Ярославской областью", "region_name_p" : u"Ярославской области"},
-87 : { "region_id" : -87, "region_name" : u"Забайкальский край", "region_name_i" : u"Забайкальский край", "region_name_r" : u"Забайкальского края", "region_name_d" : u"Забайкальскому краю", "region_name_v" : u"Забайкальского края", "region_name_t" : u"Забайкальским краем", "region_name_p" : u"Забайкальском крае"},
-86 : { "region_id" : -86, "region_name" : u"Челябинская область", "region_name_i" : u"Челябинская область", "region_name_r" : u"Челябинской области", "region_name_d" : u"Челябинской области", "region_name_v" : u"Челябинскую область", "region_name_t" : u"Челябинской областью", "region_name_p" : u"Челябинской области"},
-85 : { "region_id" : -85, "region_name" : u"Сахалинская область", "region_name_i" : u"Сахалинская область", "region_name_r" : u"Сахалинской области", "region_name_d" : u"Сахалинской области", "region_name_v" : u"Сахалинскую область", "region_name_t" : u"Сахалинской областью", "region_name_p" : u"Сахалинской области"},
-84 : { "region_id" : -84, "region_name" : u"Пензенская область", "region_name_i" : u"Пензенская область", "region_name_r" : u"Пензенской области", "region_name_d" : u"Пензенской области", "region_name_v" : u"Пензенскую область", "region_name_t" : u"Пензенской областью", "region_name_p" : u"Пензенской области"},
-83 : { "region_id" : -83, "region_name" : u"Орловская область", "region_name_i" : u"Орловская область", "region_name_r" : u"Орловской области", "region_name_d" : u"Орловской области", "region_name_v" : u"Орловскую область", "region_name_t" : u"Орловской областью", "region_name_p" : u"Орловской области"},
-82 : { "region_id" : -82, "region_name" : u"Оренбургская область", "region_name_i" : u"Оренбургская область", "region_name_r" : u"Оренбургской области", "region_name_d" : u"Оренбургской области", "region_name_v" : u"Оренбургскую область", "region_name_t" : u"Оренбургской областью", "region_name_p" : u"Оренбургской области"},
-81 : { "region_id" : -81, "region_name" : u"Омская область", "region_name_i" : u"Омская область", "region_name_r" : u"Омской области", "region_name_d" : u"Омской области", "region_name_v" : u"Омскую область", "region_name_t" : u"Омской областью", "region_name_p" : u"Омской области"},
-80 : { "region_id" : -80, "region_name" : u"Новосибирская область", "region_name_i" : u"Новосибирская область", "region_name_r" : u"Новосибирской области", "region_name_d" : u"Новосибирской области", "region_name_v" : u"Новосибирскую область", "region_name_t" : u"Новосибирской областью", "region_name_p" : u"Новосибирской области"},
-79 : { "region_id" : -79, "region_name" : u"Новгородская область", "region_name_i" : u"Новгородская область", "region_name_r" : u"Новгородской области", "region_name_d" : u"Новгородской области", "region_name_v" : u"Новгородскую область", "region_name_t" : u"Новгородской областью", "region_name_p" : u"Новгородской области"},
-78 : { "region_id" : -78, "region_name" : u"Нижегородская область", "region_name_i" : u"Нижегородская область", "region_name_r" : u"Нижегородской области", "region_name_d" : u"Нижегородской области", "region_name_v" : u"Нижегородскую область", "region_name_t" : u"Нижегородской областью", "region_name_p" : u"Нижегородской области"},
-77 : { "region_id" : -77, "region_name" : u"Мурманская область", "region_name_i" : u"Мурманская область", "region_name_r" : u"Мурманской области", "region_name_d" : u"Мурманской области", "region_name_v" : u"Мурманскую область", "region_name_t" : u"Мурманской областью", "region_name_p" : u"Мурманской области"},
-76 : { "region_id" : -76, "region_name" : u"Магаданская область", "region_name_i" : u"Магаданская область", "region_name_r" : u"Магаданской области", "region_name_d" : u"Магаданской области", "region_name_v" : u"Магаданскую область", "region_name_t" : u"Магаданской областью", "region_name_p" : u"Магаданской области"},
-75 : { "region_id" : -75, "region_name" : u"Липецкая область", "region_name_i" : u"Липецкая область", "region_name_r" : u"Липецкой области", "region_name_d" : u"Липецкой области", "region_name_v" : u"Липецкую область", "region_name_t" : u"Липецкой областью", "region_name_p" : u"Липецкой области"},
-74 : { "region_id" : -74, "region_name" : u"Курская область", "region_name_i" : u"Курская область", "region_name_r" : u"Курской области", "region_name_d" : u"Курской области", "region_name_v" : u"Курскую область", "region_name_t" : u"Курской областью", "region_name_p" : u"Курской области"},
-73 : { "region_id" : -73, "region_name" : u"Курганская область", "region_name_i" : u"Курганская область", "region_name_r" : u"Курганской области", "region_name_d" : u"Курганской области", "region_name_v" : u"Курганскую область", "region_name_t" : u"Курганской областью", "region_name_p" : u"Курганской области"},
-72 : { "region_id" : -72, "region_name" : u"Камчатский край", "region_name_i" : u"Камчатский край", "region_name_r" : u"Камчатского края", "region_name_d" : u"Камчатскому краю", "region_name_v" : u"Камчатского края", "region_name_t" : u"Камчатским краем", "region_name_p" : u"Камчатском крае"},
-71 : { "region_id" : -71, "region_name" : u"Калининградская область", "region_name_i" : u"Калининградская область", "region_name_r" : u"Калининградской области", "region_name_d" : u"Калининградской области", "region_name_v" : u"Калининградскую область", "region_name_t" : u"Калининградской областью", "region_name_p" : u"Калининградской области"},
-70 : { "region_id" : -70, "region_name" : u"Иркутская область", "region_name_i" : u"Иркутская область", "region_name_r" : u"Иркутской области", "region_name_d" : u"Иркутской области", "region_name_v" : u"Иркутскую область", "region_name_t" : u"Иркутской областью", "region_name_p" : u"Иркутской области"},
-69 : { "region_id" : -69, "region_name" : u"Ивановская область", "region_name_i" : u"Ивановская область", "region_name_r" : u"Ивановской области", "region_name_d" : u"Ивановской области", "region_name_v" : u"Ивановскую область", "region_name_t" : u"Ивановской областью", "region_name_p" : u"Ивановской области"},
-67 : { "region_id" : -67, "region_name" : u"Волгоградская область", "region_name_i" : u"Волгоградская область", "region_name_r" : u"Волгоградской области", "region_name_d" : u"Волгоградской области", "region_name_v" : u"Волгоградскую область", "region_name_t" : u"Волгоградской областью", "region_name_p" : u"Волгоградской области"},
-66 : { "region_id" : -66, "region_name" : u"Владимирская область", "region_name_i" : u"Владимирская область", "region_name_r" : u"Владимирской области", "region_name_d" : u"Владимирской области", "region_name_v" : u"Владимирскую область", "region_name_t" : u"Владимирской областью", "region_name_p" : u"Владимирской области"},
-65 : { "region_id" : -65, "region_name" : u"Брянская область", "region_name_i" : u"Брянская область", "region_name_r" : u"Брянской области", "region_name_d" : u"Брянской области", "region_name_v" : u"Брянскую область", "region_name_t" : u"Брянской областью", "region_name_p" : u"Брянской области"},
-64 : { "region_id" : -64, "region_name" : u"Белгородская область", "region_name_i" : u"Белгородская область", "region_name_r" : u"Белгородской области", "region_name_d" : u"Белгородской области", "region_name_v" : u"Белгородскую область", "region_name_t" : u"Белгородской областью", "region_name_p" : u"Белгородской области"},
-63 : { "region_id" : -63, "region_name" : u"Астраханская область", "region_name_i" : u"Астраханская область", "region_name_r" : u"Астраханской области", "region_name_d" : u"Астраханской области", "region_name_v" : u"Астраханскую область", "region_name_t" : u"Астраханской областью", "region_name_p" : u"Астраханской области"},
-62 : { "region_id" : -62, "region_name" : u"Амурская область", "region_name_i" : u"Амурская область", "region_name_r" : u"Амурской области", "region_name_d" : u"Амурской области", "region_name_v" : u"Амурскую область", "region_name_t" : u"Амурской областью", "region_name_p" : u"Амурской области"},
-61 : { "region_id" : -61, "region_name" : u"Хабаровский край", "region_name_i" : u"Хабаровский край", "region_name_r" : u"Хабаровского края", "region_name_d" : u"Хабаровскому краю", "region_name_v" : u"Хабаровского края", "region_name_t" : u"Хабаровским краем", "region_name_p" : u"Хабаровском крае"},
-60 : { "region_id" : -60, "region_name" : u"Приморский край", "region_name_i" : u"Приморский край", "region_name_r" : u"Приморского края", "region_name_d" : u"Приморскому краю", "region_name_v" : u"Приморского края", "region_name_t" : u"Приморским краем", "region_name_p" : u"Приморском крае"},
-59 : { "region_id" : -59, "region_name" : u"Чувашия республика", "region_name_i" : u"Республика Чувашия", "region_name_r" : u"Республики Чувашии", "region_name_d" : u"Республике Чувашии", "region_name_v" : u"Республику Чувашию", "region_name_t" : u"Республикой Чувашией", "region_name_p" : u"Республике Чувашии"},
-58 : { "region_id" : -58, "region_name" : u"Чеченская республика", "region_name_i" : u"Чеченская Республика", "region_name_r" : u"Чеченской Республики", "region_name_d" : u"Чеченской Республике", "region_name_v" : u"Чеченскую Республику", "region_name_t" : u"Чеченской Республикой", "region_name_p" : u"Чеченской Республике"},
-57 : { "region_id" : -57, "region_name" : u"Хакасия республика", "region_name_i" : u"Республика Хакасия", "region_name_r" : u"Республики Хакасии", "region_name_d" : u"Республике Хакасии", "region_name_v" : u"Республику Хакасию", "region_name_t" : u"Республикой Хакасией", "region_name_p" : u"Республике Хакасии"},
-56 : { "region_id" : -56, "region_name" : u"Удмуртская республика", "region_name_i" : u"Удмуртская Республика", "region_name_r" : u"Удмуртской Республики", "region_name_d" : u"Удмуртской Республике", "region_name_v" : u"Удмуртскую Республику", "region_name_t" : u"Удмуртской Республикой", "region_name_p" : u"Удмуртской Республике"},
-55 : { "region_id" : -55, "region_name" : u"Тыва республика", "region_name_i" : u"Республика Тыва", "region_name_r" : u"Республики Тыва", "region_name_d" : u"Республике Тыва", "region_name_v" : u"Республику Тыва", "region_name_t" : u"Республикой Тыва", "region_name_p" : u"Республике Тыве"},
-54 : { "region_id" : -54, "region_name" : u"Татарстан республика", "region_name_i" : u"Республика Татарстан", "region_name_r" : u"Республики Татарстан", "region_name_d" : u"Республике Татарстан", "region_name_v" : u"Республику Татарстан", "region_name_t" : u"Республикой Татарстан", "region_name_p" : u"Республике Татарстан"},
-53 : { "region_id" : -53, "region_name" : u"Северная Осетия (Алания) республика", "region_name_i" : u"Респ. Северная Осетия Алания", "region_name_r" : u"Респ. Северная Осетия Алания", "region_name_d" : u"Респ. Северная Осетия Алания", "region_name_v" : u"Респ. Северная Осетия Алания", "region_name_t" : u"Респ. Северная Осетия Алания", "region_name_p" : u"Респ. Северная Осетия Алания"},
-52 : { "region_id" : -52, "region_name" : u"Саха (Якутия) республика", "region_name_i" : u"Республика Саха Якутия", "region_name_r" : u"Республики Саха Якутии", "region_name_d" : u"Республике Саха Якутии", "region_name_v" : u"Республику Саха Якутию", "region_name_t" : u"Республикой Саха Якутией", "region_name_p" : u"Республике Саха Якутии"},
-51 : { "region_id" : -51, "region_name" : u"Марий Эл республика", "region_name_i" : u"Республика Марий Эл", "region_name_r" : u"Республики Мария Эл", "region_name_d" : u"Республике Марию Эл", "region_name_v" : u"Республику Мария Эл", "region_name_t" : u"Республикой Марием Эл", "region_name_p" : u"Республике Марии Эл"},
-50 : { "region_id" : -50, "region_name" : u"Карачаево-Черкесская республика", "region_name_i" : u"Карачаево-Черкесская Республика", "region_name_r" : u"Карачаево-Черкесской Республики", "region_name_d" : u"Карачаево-Черкесской Республике", "region_name_v" : u"Карачаево-Черкесскую Республику", "region_name_t" : u"Карачаево-Черкесской Республикой", "region_name_p" : u"Карачаево-Черкесской Республике"},
-49 : { "region_id" : -49, "region_name" : u"Калмыкия республика", "region_name_i" : u"Республика Калмыкия", "region_name_r" : u"Республики Калмыкии", "region_name_d" : u"Республике Калмыкии", "region_name_v" : u"Республику Калмыкию", "region_name_t" : u"Республикой Калмыкией", "region_name_p" : u"Республике Калмыкии"},
-48 : { "region_id" : -48, "region_name" : u"Кабардино-Балкария республика", "region_name_i" : u"Республика Кабардино-Балкария", "region_name_r" : u"Республики Кабардина-Балкарии", "region_name_d" : u"Республике Кабардино-Балкарии", "region_name_v" : u"Республику Кабардино-Балкарию", "region_name_t" : u"Республикой Кабардино-Балкарией", "region_name_p" : u"Республике Кабардине-Балкарии"},
-47 : { "region_id" : -47, "region_name" : u"Ингушетия республика", "region_name_i" : u"Республика Ингушетия", "region_name_r" : u"Республики Ингушетии", "region_name_d" : u"Республике Ингушетии", "region_name_v" : u"Республику Ингушетию", "region_name_t" : u"Республикой Ингушетией", "region_name_p" : u"Республике Ингушетии"},
-46 : { "region_id" : -46, "region_name" : u"Дагестан республика", "region_name_i" : u"Республика Дагестан", "region_name_r" : u"Республики Дагестан", "region_name_d" : u"Республике Дагестан", "region_name_v" : u"Республику Дагестан", "region_name_t" : u"Республикой Дагестан", "region_name_p" : u"Республике Дагестан"},
-45 : { "region_id" : -45, "region_name" : u"Алтай республика", "region_name_i" : u"Республика Алтай", "region_name_r" : u"Республики Алтай", "region_name_d" : u"Республике Алтай", "region_name_v" : u"Республику Алтай", "region_name_t" : u"Республикой Алтай", "region_name_p" : u"Республике Алтай"},
-44 : { "region_id" : -44, "region_name" : u"Бурятия республика", "region_name_i" : u"Республика Бурятия", "region_name_r" : u"Республики Бурятии", "region_name_d" : u"Республике Бурятии", "region_name_v" : u"Республику Бурятию", "region_name_t" : u"Республикой Бурятией", "region_name_p" : u"Республике Бурятии"},
-43 : { "region_id" : -43, "region_name" : u"Башкортостан республика", "region_name_i" : u"Республика Башкортостан", "region_name_r" : u"Республики Башкортостан", "region_name_d" : u"Республике Башкортостан", "region_name_v" : u"Республику Башкортостан", "region_name_t" : u"Республикой Башкортостан", "region_name_p" : u"Республике Башкортостан"},
-42 : { "region_id" : -42, "region_name" : u"Адыгея республика", "region_name_i" : u"Республика Адыгея", "region_name_r" : u"Республики Адыгеи", "region_name_d" : u"Республике Адыгее", "region_name_v" : u"Республику Адыгею", "region_name_t" : u"Республикой Адыгеей", "region_name_p" : u"Республике Адыгее"},
-41 : { "region_id" : -41, "region_name" : u"Красноярский край", "region_name_i" : u"Красноярский край", "region_name_r" : u"Красноярского края", "region_name_d" : u"Красноярскому краю", "region_name_v" : u"Красноярского края", "region_name_t" : u"Красноярским краем", "region_name_p" : u"Красноярском крае"},
-40 : { "region_id" : -40, "region_name" : u"Краснодарский край", "region_name_i" : u"Краснодарский край", "region_name_r" : u"Краснодарского края", "region_name_d" : u"Краснодарскому краю", "region_name_v" : u"Краснодарского края", "region_name_t" : u"Краснодарским краем", "region_name_p" : u"Краснодарском крае"},
-39 : { "region_id" : -39, "region_name" : u"Костромская область", "region_name_i" : u"Костромская область", "region_name_r" : u"Костромской области", "region_name_d" : u"Костромской области", "region_name_v" : u"Костромскую область", "region_name_t" : u"Костромской областью", "region_name_p" : u"Костромской области"},
-38 : { "region_id" : -38, "region_name" : u"Кировская область", "region_name_i" : u"Кировская область", "region_name_r" : u"Кировской области", "region_name_d" : u"Кировской области", "region_name_v" : u"Кировскую область", "region_name_t" : u"Кировской областью", "region_name_p" : u"Кировской области"},
-37 : { "region_id" : -37, "region_name" : u"Кемеровская область", "region_name_i" : u"Кемеровская область", "region_name_r" : u"Кемеровской области", "region_name_d" : u"Кемеровской области", "region_name_v" : u"Кемеровскую область", "region_name_t" : u"Кемеровской областью", "region_name_p" : u"Кемеровской области"},
-36 : { "region_id" : -36, "region_name" : u"Калужская область", "region_name_i" : u"Калужская область", "region_name_r" : u"Калужской области", "region_name_d" : u"Калужской области", "region_name_v" : u"Калужскую область", "region_name_t" : u"Калужской областью", "region_name_p" : u"Калужской области"},
-33 : { "region_id" : -33, "region_name" : u"Вологодская область", "region_name_i" : u"Вологодская область", "region_name_r" : u"Вологодской области", "region_name_d" : u"Вологодской области", "region_name_v" : u"Вологодскую область", "region_name_t" : u"Вологодской областью", "region_name_p" : u"Вологодской области"},
-155 : { "region_id" : -155, "region_name" : u"Волгоград регион", "region_name_i" : u"Волгоград регион", "region_name_r" : u"Волгограда региона", "region_name_d" : u"Волгограду региону", "region_name_v" : u"Волгоград регион", "region_name_t" : u"Волгоградом регионом", "region_name_p" : u"регионе Волгоград"},
-26 : { "region_id" : -26, "region_name" : u"Воронежская область", "region_name_i" : u"Воронежская область", "region_name_r" : u"Воронежской области", "region_name_d" : u"Воронежской области", "region_name_v" : u"Воронежскую область", "region_name_t" : u"Воронежской областью", "region_name_p" : u"Воронежской области"},
-153 : { "region_id" : -153, "region_name" : u"Санкт-Петербург регион", "region_name_i" : u"Санкт-Петербург регион", "region_name_r" : u"Санкт-Петербург регион", "region_name_d" : u"Санкт-Петербург регион", "region_name_v" : u"Санкт-Петербург регион", "region_name_t" : u"Санкт-Петербург регион", "region_name_p" : u"регионе Санкт-Петербург"},
-24 : { "region_id" : -24, "region_name" : u"Тульская область", "region_name_i" : u"Тульская область", "region_name_r" : u"Тульской области", "region_name_d" : u"Тульской области", "region_name_v" : u"Тульскую область", "region_name_t" : u"Тульской областью", "region_name_p" : u"Тульской области"},
-151 : { "region_id" : -151, "region_name" : u"Москва регион", "region_name_i" : u"Москва регион", "region_name_r" : u"Москвы регион", "region_name_d" : u"Москве регион", "region_name_v" : u"Москву регион", "region_name_t" : u"Москвой регион", "region_name_p" : u"регионе Москва"},
-22 : { "region_id" : -22, "region_name" : u"Тверская область", "region_name_i" : u"Тверская область", "region_name_r" : u"Тверской области", "region_name_d" : u"Тверской области", "region_name_v" : u"Тверскую область", "region_name_t" : u"Тверской областью", "region_name_p" : u"Тверской области"},
-21 : { "region_id" : -21, "region_name" : u"Свердловская область", "region_name_i" : u"Свердловская область", "region_name_r" : u"Свердловской области", "region_name_d" : u"Свердловской области", "region_name_v" : u"Свердловскую область", "region_name_t" : u"Свердловской областью", "region_name_p" : u"Свердловской области"},
-20 : { "region_id" : -20, "region_name" : u"Алтайский край", "region_name_i" : u"Алтайский край", "region_name_r" : u"Алтайского края", "region_name_d" : u"Алтайскому краю", "region_name_v" : u"Алтайского края", "region_name_t" : u"Алтайским краем", "region_name_p" : u"Алтайском крае"},
-19 : { "region_id" : -19, "region_name" : u"Тамбовская область", "region_name_i" : u"Тамбовская область", "region_name_r" : u"Тамбовской области", "region_name_d" : u"Тамбовской области", "region_name_v" : u"Тамбовскую область", "region_name_t" : u"Тамбовской областью", "region_name_p" : u"Тамбовской области"},
-18 : { "region_id" : -18, "region_name" : u"Коми республика", "region_name_i" : u"Республика Коми", "region_name_r" : u"Республики Коми", "region_name_d" : u"Республике Коми", "region_name_v" : u"Республику Коми", "region_name_t" : u"Республикой Коми", "region_name_p" : u"Республике Коми"},
-17 : { "region_id" : -17, "region_name" : u"Ямало-Ненец. авт. окр.", "region_name_i" : u"Ямало-Ненец. авт. окр.", "region_name_r" : u"Ямало-Ненец. авт. окр.", "region_name_d" : u"Ямало-Ненец. авт. окр.", "region_name_v" : u"Ямало-Ненец. авт. окр.", "region_name_t" : u"Ямало-Ненец. авт. окр.", "region_name_p" : u"Ямало-Ненец. авт. окр."},
-16 : { "region_id" : -16, "region_name" : u"Ханты-Манс. авт. окр.", "region_name_i" : u"Ханты-Манс. авт. окр.", "region_name_r" : u"Ханты-Манс. авт. окр.", "region_name_d" : u"Ханты-Манс. авт. окр.", "region_name_v" : u"Ханты-Манс. авт. окр.", "region_name_t" : u"Ханты-Манс. авт. окр.", "region_name_p" : u"Ханты-Манс. авт. окр."},
-15 : { "region_id" : -15, "region_name" : u"Тюменская область", "region_name_i" : u"Тюменская область", "region_name_r" : u"Тюменской области", "region_name_d" : u"Тюменской области", "region_name_v" : u"Тюменскую область", "region_name_t" : u"Тюменской областью", "region_name_p" : u"Тюменской области"},
-14 : { "region_id" : -14, "region_name" : u"Ставропольский край", "region_name_i" : u"Ставропольский край", "region_name_r" : u"Ставропольского края", "region_name_d" : u"Ставропольскому краю", "region_name_v" : u"Ставропольского края", "region_name_t" : u"Ставропольским краем", "region_name_p" : u"Ставропольском крае"},
-13 : { "region_id" : -13, "region_name" : u"Смоленская область", "region_name_i" : u"Смоленская область", "region_name_r" : u"Смоленской области", "region_name_d" : u"Смоленской области", "region_name_v" : u"Смоленскую область", "region_name_t" : u"Смоленской областью", "region_name_p" : u"Смоленской области"},
-11 : { "region_id" : -11, "region_name" : u"Саратовская область", "region_name_i" : u"Саратовская область", "region_name_r" : u"Саратовской области", "region_name_d" : u"Саратовской области", "region_name_v" : u"Саратовскую область", "region_name_t" : u"Саратовской областью", "region_name_p" : u"Саратовской области"},
-10 : { "region_id" : -10, "region_name" : u"Мордовия республика", "region_name_i" : u"Республика Мордовия", "region_name_r" : u"Республики Мордовии", "region_name_d" : u"Республике Мордовии", "region_name_v" : u"Республику Мордовию", "region_name_t" : u"Республикой Мордовией", "region_name_p" : u"Республике Мордовии"},
-9 : { "region_id" : -9, "region_name" : u"Самарская область", "region_name_i" : u"Самарская область", "region_name_r" : u"Самарской области", "region_name_d" : u"Самарской области", "region_name_v" : u"Самарскую область", "region_name_t" : u"Самарской областью", "region_name_p" : u"Самарской области"},
-8 : { "region_id" : -8, "region_name" : u"Рязанская область", "region_name_i" : u"Рязанская область", "region_name_r" : u"Рязанской области", "region_name_d" : u"Рязанской области", "region_name_v" : u"Рязанскую область", "region_name_t" : u"Рязанской областью", "region_name_p" : u"Рязанской области"},
-7 : { "region_id" : -7, "region_name" : u"Ростовская область", "region_name_i" : u"Ростовская область", "region_name_r" : u"Ростовской области", "region_name_d" : u"Ростовской области", "region_name_v" : u"Ростовскую область", "region_name_t" : u"Ростовской областью", "region_name_p" : u"Ростовской области"},
-6 : { "region_id" : -6, "region_name" : u"Архангельская область", "region_name_i" : u"Архангельская область", "region_name_r" : u"Архангельской области", "region_name_d" : u"Архангельской области", "region_name_v" : u"Архангельскую область", "region_name_t" : u"Архангельской областью", "region_name_p" : u"Архангельской области"},
-5 : { "region_id" : -5, "region_name" : u"Псковская область", "region_name_i" : u"Псковская область", "region_name_r" : u"Псковской области", "region_name_d" : u"Псковской области", "region_name_v" : u"Псковскую область", "region_name_t" : u"Псковской областью", "region_name_p" : u"Псковской области"},
-4 : { "region_id" : -4, "region_name" : u"Карелия республика", "region_name_i" : u"Республика Карелия", "region_name_r" : u"Республики Карелии", "region_name_d" : u"Республике Карелии", "region_name_v" : u"Республику Карелию", "region_name_t" : u"Республикой Карелией", "region_name_p" : u"Республике Карелии"},
-3 : { "region_id" : -3, "region_name" : u"Пермский край", "region_name_i" : u"Пермский край", "region_name_r" : u"Пермского края", "region_name_d" : u"Пермскому краю", "region_name_v" : u"Пермского края", "region_name_t" : u"Пермским краем", "region_name_p" : u"Пермском крае"},
-2 : { "region_id" : -2, "region_name" : u"Ленинградская область", "region_name_i" : u"Ленинградская область", "region_name_r" : u"Ленинградской области", "region_name_d" : u"Ленинградской области", "region_name_v" : u"Ленинградскую область", "region_name_t" : u"Ленинградской областью", "region_name_p" : u"Ленинградской области"}
}


from scripts.yaapi import ya
import codecs
import os

def get_regions_with_padezhami():
	file_path = os.path.join(os.path.dirname(__file__), "regions.data")
	print(file_path)
	with codecs.open(file_path, "w", encoding="utf-8") as f:
		for region in regions.values():
			r_id = region.get("region_id")
			r_name = region.get("region_name")
			(i, r, d, v, t, p) = ya.fetch_padezhy(r_name)
			f.write(u'''{0} : {{ "region_id" : {0}, "region_name" : u"{1}", "region_name_i" : u"{2}", "region_name_r" : u"{3}", "region_name_d" : u"{4}", "region_name_v" : u"{5}", "region_name_t" : u"{6}", "region_name_p" : u"{7}"}},\n'''.format(r_id, r_name, i, r, d, v, t, p))

if __name__ == '__main__':
	get_regions_with_padezhami()